apiVersion: apps/v1
kind: Deployment
metadata:
  name: basic-auth
  labels:
    app: basic-auth
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: basic-auth
  template:
    metadata:
      labels:
        app: basic-auth
    spec:
      tolerations:
      - key: cloud.google.com/gke-nodepool
        operator: Equal
        value: services-pool
        effect: NoSchedule
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: cloud.google.com/gke-preemptible
                operator: DoesNotExist
              - key: cloud.google.com/gke-nodepool
                operator: In
                values:
                - services-pool
      containers:
      - name: nginx
        image: nginx:stable
        imagePullPolicy: Always
        securityContext:
          allowPrivilegeEscalation: false
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        volumeMounts:
        - name: basic-auth-secret
          mountPath: /etc/nginx/conf.d/.htpasswd
          subPath: .htpasswd
          readOnly: true
        - name: basic-auth-config
          mountPath: /etc/nginx/conf.d/default.conf
          subPath: default.conf
          readOnly: true
        resources:
          limits:
            cpu: 200m
            memory: 256Mi
          requests:
            cpu: 100m
            memory: 128Mi
      volumes:
        - name: basic-auth-secret
          secret:
            secretName: basic-auth-secret
        - name: basic-auth-config
          configMap:
              name: basic-auth-config
